# Generated by Django 4.2.11 on 2024-04-29 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('overtime_pay', models.FloatField(blank=True, null=True)),
                ('allowance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(blank=True, max_length=300, null=True)),
                ('brand', models.CharField(blank=True, max_length=300, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('size', models.CharField(blank=True, max_length=300, null=True)),
                ('mouth_size', models.CharField(blank=True, max_length=300, null=True)),
                ('color', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('date_range', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('pay_cycle', models.IntegerField()),
                ('rate', models.FloatField()),
                ('earnings_allowance', models.FloatField()),
                ('deductions_tax', models.FloatField()),
                ('deductions_health', models.FloatField()),
                ('pag_ibig', models.FloatField()),
                ('sss', models.FloatField()),
                ('overtime', models.FloatField()),
                ('total_pay', models.FloatField()),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee')),
            ],
        ),
    ]
