# Generated by Django 5.0.1 on 2024-04-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbottle',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='WaterBottle',
        ),
    ]
